const TRIVIAL_PARTITION_KEY = "0";
const MAX_PARTITION_KEY_LENGTH = 256;
const HASING_ALGORITHM = "sha3-512";
const HASING_ENCODING = "hex";

module.exports = {
    TRIVIAL_PARTITION_KEY,
    MAX_PARTITION_KEY_LENGTH,
    HASING_ALGORITHM,
    HASING_ENCODING,
}
